set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR AMD64)
set(CMAKE_C_COMPILER clang-cl-19)
set(CMAKE_CXX_COMPILER clang-cl-19)
set(CMAKE_LINKER lld-link)
set(CMAKE_AR llvm-lib-19)
set(CMAKE_RC_COMPILER llvm-rc-19)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
if(NOT DEFINED ENV{XWIN_ROOT})
  message(FATAL_ERROR "Set XWIN_ROOT to the xwin splat directory")
endif()
set(_sdk "$ENV{XWIN_ROOT}")
set(CMAKE_C_FLAGS_INIT "--target=x86_64-pc-windows-msvc /imsvc\"${_sdk}/crt/include\" /imsvc\"${_sdk}/sdk/include/ucrt\" /imsvc\"${_sdk}/sdk/include/um\" /imsvc\"${_sdk}/sdk/include/shared\" /imsvc\"${_sdk}/sdk/include/winrt\"")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(_libs "/libpath:\"${_sdk}/crt/lib/x86_64\" /libpath:\"${_sdk}/sdk/lib/ucrt/x86_64\" /libpath:\"${_sdk}/sdk/lib/um/x86_64\"")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${_libs}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_libs}")
